### ISSUE TITLE
Google DAI Hls

### ISSUE THREAD

**Issue by thumb777** [thumb777/Adaptive-video-live-stream#1]
Hi! Someone know how Google DAI Hls conditioning works for SSAI with DRM? How Google can cut a video/audio segment encrypted

**Comment by thumb777** [comment]
My understanding was that Google DAI was unable to split segments on the fly.  That you needed you transcoding/encoder to pre-split the segment in preparation.  Things may have changed however.

**Comment by thumb777** [comment]
In my thought, Google DAI for SSAI by segmenting and independently encrypting video/audio streams for seamless integration with DRM systems, thus enabling precise ad insertion even in encrypted content.

**Comment by smarter777** [comment]
In my thought, Google DAI for SSAI by segmenting and independently encrypting video/audio streams for seamless integration with DRM systems, thus enabling precise ad insertion even in encrypted content.

**Comment by thumb777** [comment]
sorry let's discuss on discussion page
